name = "DC1"

architectural-decisions = [

  "rack-dual-leaf-lag",         # each rack with have 2 leaf switch; peer interfaces configured in LAG
                                # the lag name is currently hardcoded to Lag0 in cabling.py

  # "rack-dual-leaf",             # each rack with have 2 leaf switch; peer interfaces p2p

  "rack-leaf-asn-shared",       # leaf devices in rack share the same ASN
  # "rack-leaf-asn-unique",       # each leaf gets a unique ASN

  "spine-asn-unique"            # each spine gets a unqiue ASN
  # "spine-asn-shared"          # all spines use the same ASN

]

[topology]

    # spines are hardcoded to use an Arista 32x100g switch
    spines = 2

    # racks are hardcoded to use two Arista 48x[10|25] + 12x100g switches
    racks = 8

    leaf-spine-interface-count = 1
    leaf-pair-interface-count = 2

[ip-assignments]

    # 30 hosts for the loopbacks from this subnet
    loopback_ip_subnet = "12.12.1.0/27"

    # need a subnet for making p2p interface IPs.  This /24 will be
    # chopped into /31 spaces for each p2p link.  This pool is used for leaf-spine and leaf-pair
    # interface connections.

    fabric_ip_subnet = "12.12.2.0/24"


[asn-values]
    spine-range = [10, 20]
    leaf-range = [64512, 65600]

[vlans]

    [vlans.alpha]
        description = "this is alpha"
        vlan_id = 10
        ip_gateway = "1.1.1.1"

    [vlans.beta]
        description = "this is beta"
        vlan_id = 20
        ip_gateway = "1.2.1.1"

    [vlans.omega]
        description = "this is omega"
        vlan_id = 30

    [vlans.red]
        vlan_id = 100

    [vlans.green]
        vlan_id = 150

    [vlans.blue]
        vlan_id = 200

[vlan-groups]

    [vlan-groups.greek]
        description = 'The Greeks!'
        members = ["alpha", "beta", "omega"]

    [vlan-groups.colors]
        description = 'Colors are pretty'
        members = ["red", "green", "blue"]


[vlan-assignments]

    [vlan-assignments.leaf01]
        Ethernet1 = "alpha"         # will be access mode
        Ethernet2 = "beta"          # will be access mode
        Ethernet3 = "greek"         # will be trunk mode
        Ethernet4 = ["beta"]        # will be trunk mode because single item in list

    [vlan-assignments.leaf07]
        Ethernet1 = ["omega", "red"]
        Ethernet2 = ['greek', 'blue']
        Ethernet3 = ['greek', 'colors']
